services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "5004:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
# тома, которые будут использовать сервисы
volumes:
  jenkins_home: # название тома для хранения данных jenkins